NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 python -m torch.distributed.launch --use-env --nproc_per_node=7 --master_port='29504' main_finetune_distill.py \
    --accum_iter 2 \
    --batch_size 64 \
    --model swin_tiny_dvs --dataset cifar100 --nb_classes 100 \
    --model_teacher swin_tiny_dvs \
    --finetune /data/kang_you1/SpikeZIP_transformer_resnet1/output/T-SNN_swin_tiny_dvs_cifar100_relu_ANN_act32_weightbit32_NormTypedyt_NIPS/checkpoint-best.pth \
    --pretrain_teacher /data/kang_you1/SpikeZIP_transformer_resnet1/output/T-SNN_swin_tiny_dvs_cifar100_relu_ANN_act32_weightbit32_NormTypedyt_NIPS/checkpoint-best.pth \
    --epochs 100 \
    --blr 1e-4 --layer_decay 1.0 --warmup_epochs 0 \
    --weight_decay 0.5 --drop_path 0.1 --mixup 0.5 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /data --output_dir /data/kang_you1/SpikeZIP_transformer_resnet1/output/ --log_dir /data/kang_you1/SpikeZIP_transformer_resnet1/output/ \
    --mode "QANN_QAT" --level 10 --act_layer relu --remove_softmax --NormType dyt --weight_quantization_bit 32 --act_layer_teacher relu --temp 2.0 --print_freq 200