NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 --master_port='29502' main_finetune.py \
    --accum_iter 4 \
    --batch_size 32 \
    --model vit_small_patch16 \
    --finetune /home/kang_you/SpikeZIP_transformer/output/with_softmax_less_myquan/T-SNN_vit_small_patch16_imagenet_relu_QANN_QAT_act8_weightbit32/checkpoint-199.pth \
    --resume /home/kang_you/SpikeZIP_transformer/output/with_softmax_less_myquan/T-SNN_vit_small_patch16_imagenet_relu_QANN_QAT_act8_weightbit32/checkpoint-199.pth \
    --epochs 100 \
    --blr 3.536e-4 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /data/ --output_dir /home/kang_you/SpikeZIP_transformer/output/IF_neuron_abla --log_dir /home/kang_you/SpikeZIP_transformer/output/IF_neuron_abla \
    --mode "SNN" --act_layer relu --eval --time_step 31 --encoding_type rate --level 8 --define_params --mean 0.5 0.5 0.5 --std 0.5 0.5 0.5 --remove_softmax