NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port='29500' main_finetune_distill.py \
    --accum_iter 4 \
    --batch_size 192 \
    --model vit_small_patch16 \
    --model_teacher vit_small_patch16 \
    --finetune /home/kang_you1/vit_small_patch16_224_no_softmax_no_ln_1744544323.5130663_in21k_74.93.pth \
    --pretrain_teacher /data/vit-small-patch16-relu-82.34.pth \
    --epochs 20 \
    --blr 1e-4 --layer_decay 0.65 --warmup_epochs 0 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /data/ --output_dir /home/kang_you/SpikeZIP_transformer/output/no_softmax_output_ReLU/ --log_dir /home/kang_you/SpikeZIP_transformer/output/no_softmax_output_ReLU/ \
    --mode "ANN" --act_layer relu --remove_softmax --NormType mylayernorm --eval --act_layer_teacher gelu --temp 2.0 --wandb --print_freq 200 --define_params --mean 0.5 0.5 0.5 --std 0.5 0.5 0.5