NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 python -m torch.distributed.launch --nproc_per_node=7 --use-env --master_port='29500' main_finetune_distill.py \
    --accum_iter 1 \
    --batch_size 144 \
    --model vit_base_patch16 \
    --model_teacher vit_small_patch16 \
    --finetune /data1/kang_you/SpikeZIP_transformer_resnet1/output/T-SNN_swin_tiny_imagenet_relu_QANN_QAT_act14_weightbit32_NormTypedyt_NIPS \
    --epochs 100 \
    --blr 5e-4 --layer_decay 0.65 --warmup_epochs 5 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 --smoothing 0.1 --clip_grad 20 \
    --dist_eval --data_path /data/ImageNet --output_dir /data1/kang_you/SpikeZIP_transformer_resnet1/output/ --log_dir /data/kang_you1/SpikeZIP_transformer_resnet1/output/ \
    --mode "ANN" --act_layer relu --remove_softmax --NormType mybatchnorm --act_layer_teacher relu --temp 2.0 --print_freq 200