NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=1,3,4,5,6,7, python -m torch.distributed.run --nproc_per_node=6 --master_port='29500' main_finetune_distill_prune.py \
    --accum_iter 4 \
    --batch_size 64 \
    --model vit_small_patch16 \
    --model_teacher vit_small_patch16 \
    --finetune /home/kang_you/SpikeZIP_transformer/output/no_softmax/T-SNN_vit_small_patch16_imagenet_relu_ANN_act32_weightbit32/checkpoint-99.pth \
    --pretrain_teacher /data1/vit-small-patch16-relu-82.34.pth \
    --epochs 5 \
    --blr 1.5e-4 --layer_decay 0.65 --warmup_epochs 0 \
    --weight_decay 0.01 --drop_path 0.05 --drop_rate 0.0 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /data1/ImageNet/ --output_dir /home/kang_you/SpikeZIP_transformer/output/with_softmax --log_dir /home/kang_you/SpikeZIP_transformer/output/with_softmax \
    --mode "QANN_QAT" --remove_softmax --ratio 0.5 --level 8 --act_layer relu --act_layer_teacher relu --temp 2.0 --wandb --print_freq 200 --define_params --mean 0.5 0.5 0.5 --std 0.5 0.5 0.5