NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.run --nproc_per_node=4 --master_port='29500' main_finetune_distill.py \
    --accum_iter 4 \
    --batch_size 64 \
    --model vit_small_patch16 \
    --model_teacher vit_base_patch16 \
    --finetune /home/kang_you/SpikeZIP_transformer/output/no_softmax_powerNorm_output_ReLU/T-SNN_vit_small_patch16_imagenet_relu_ANN_act32_weightbit32/checkpoint-39.pth \
    --pretrain_teacher /home/kang_you/SpikeZIP_transformer/timmvit_base_patch16_224.augreg2_in21k_ft_in1k.bin \
    --epochs 200 \
    --blr 1.5e-4 --layer_decay 0.65 --warmup_epochs 0 \
    --weight_decay 0.01 --drop_path 0.05 --drop_rate 0.0 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /data/ --output_dir /home/kang_you/SpikeZIP_transformer/output/without_softmax_powernorm --log_dir /home/kang_you/SpikeZIP_transformer/output/without_softmax_powernorm \
    --mode "QANN_QAT" --level 16 --act_layer relu --remove_softmax --NormType powernorm --act_layer_teacher gelu --temp 2.0 --wandb --print_freq 200 --define_params --mean 0.5 0.5 0.5 --std 0.5 0.5 0.5